use_frameworks!

target 'UIComposable_Example' do
  pod 'UIComposable', :path => '../'
  pod 'UIComposable/RxUI', :path => '../'
  pod 'UIComposable/DiffUI', :path => '../'

  target 'UIComposable_Tests' do
    inherit! :search_paths

    
  end
end
